version: 2
jobs:
  build:
    docker:
      - image: mmquant/cpp_dev:deb9.5
    steps:
      
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}-
      
      - checkout
      
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - run:
          name: Build project
          command: |
            mkdir build && cd build && cmake .. && make 
